# Generated by Django 4.1 on 2022-09-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticias_imagensnoticias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
