# Generated by Django 4.1 on 2022-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='preview',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
